const products = [
  {
    id: 1,
    name: "Product 1 Product 1 Product 1 Product 1",
    image:
      "https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg?auto=compress&cs=tinysrgb&w=1600",
    description: "Description of Product 1",
    brand: "Brand A",
    category: "Category X",
    price: 29.99,
    countInStock: 50,
    rating: 4.5,
    numReviews: 30,
  },
  {
    id: 2,
    name: "Product 2",
    image:
      "https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg?auto=compress&cs=tinysrgb&w=1600",
    description: "Description of Product 2",
    brand: "Brand B",
    category: "Category Y",
    price: 39.99,
    countInStock: 0,
    rating: 4.0,
    numReviews: 25,
  },
  {
    id: 3,
    name: "Product 3",
    image:
      "https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg?auto=compress&cs=tinysrgb&w=1600",
    description: "Description of Product 3",
    brand: "Brand C",
    category: "Category Z",
    price: 49.99,
    countInStock: 10,
    rating: 4.2,
    numReviews: 15,
  },
  {
    id: 4,
    name: "Product 4",
    image:
      "https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg?auto=compress&cs=tinysrgb&w=1600",
    description: "Description of Product 4",
    brand: "Brand D",
    category: "Category X",
    price: 34.99,
    countInStock: 40,
    rating: 4.7,
    numReviews: 40,
  },
  {
    id: 5,
    name: "Product 5",
    image:
      "https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg?auto=compress&cs=tinysrgb&w=1600",
    description: "Description of Product 5",
    brand: "Brand E",
    category: "Category Y",
    price: 44.99,
    countInStock: 15,
    rating: 4.3,
    numReviews: 20,
  },
  {
    id: 6,
    name: "Product 6",
    image:
      "https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg?auto=compress&cs=tinysrgb&w=1600",
    description: "Description of Product 6",
    brand: "Brand F",
    category: "Category Z",
    price: 39.99,
    countInStock: 25,
    rating: 4.4,
    numReviews: 18,
  },
  {
    id: 7,
    name: "Product 7",
    image:
      "https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg?auto=compress&cs=tinysrgb&w=1600",
    description: "Description of Product 7",
    brand: "Brand G",
    category: "Category X",
    price: 54.99,
    countInStock: 30,
    rating: 4.8,
    numReviews: 50,
  },
  {
    id: 8,
    name: "Product 8",
    image:
      "https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg?auto=compress&cs=tinysrgb&w=1600",
    description: "Description of Product 8",
    brand: "Brand H",
    category: "Category Y",
    price: 47.99,
    countInStock: 12,
    rating: 4.1,
    numReviews: 28,
  },
  {
    id: 9,
    name: "Product 9",
    image:
      "https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg?auto=compress&cs=tinysrgb&w=1600",
    description: "Description of Product 9",
    brand: "Brand I",
    category: "Category Z",
    price: 59.99,
    countInStock: 22,
    rating: 4.6,
    numReviews: 35,
  },
  {
    id: 10,
    name: "Product 10",
    image:
      "https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg?auto=compress&cs=tinysrgb&w=1600",
    description: "Description of Product 10",
    brand: "Brand J",
    category: "Category X",
    price: 24.99,
    countInStock: 60,
    rating: 4.9,
    numReviews: 60,
  },
  // You can add more products or modify existing ones as needed.
];

export default products;
